language: java

before_install:
  # download the latest android sdk and unzip
  - pwd
  - wget "http://dl.google.com/android/android-sdk_r22.0.4-linux.tgz" -O android-sdk.tgz
  - tar -zxf android-sdk.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --filter android-10,android-17,build-tools-17.0.0,platform-tools --force --no-ui
  - echo $ANDROID_HOME
  - echo $PATH
  - ls -l android-sdk-linux/build-tools/17.0.0/aapt
  - ls -l android-sdk-linux/platform-tools/adb
  - android update project -p . --subprojects -t android-17 -n GatekeeperAndroid

script: ant debug

notifications:
  recipients:
    anthony+travisci@agargiulo.com

  on_success: change
  on_failure: change
