language: android
android:
    components:
        # Use the latest revision for the platform tools and SDK tools
        - platform-tools
        - tools
        # I'm using Android 4.4.2 (Level 19)
        - build-tools-19.1.0
        - android-19

script: ant debug

notifications:
  recipients:
    anthony+travisci@agargiulo.com

  irc:
    channels:
    - "skynet.csh.rit.edu#usercenter"
    template:
    - "%{repository}#%{build_number}: %{author}: %{branch}: %{message}"
