language: java

before_install:
  # download the latest android sdk and unzip
  - echo 4a5db98a58c68c24e66f04f07ac77da5  android-sdk.tgz > android-sdk.tgz.md5
  - wget "http://dl.google.com/android/android-sdk_r22.0.4-linux.tgz" -O android-sdk.tgz
  - md5sum -c android-sdk.tgz.md5
  - tar -zxf android-sdk.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk -u -n --filter 'android-17,android-10,platform,platform-tool'
