language: java

before_install:
  # download the latest android sdk and unzip
  - wget "http://dl.google.com/android/android-sdk_r22.0.4-linux.tgz" -O android-sdk.tgz
  - tar -zxf android-sdk.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --filter android-10,android-17,build-tools-17.0.0,platform-tools --force --no-ui
  - android update project -p . --subprojects -t 17 -n GatekeeperAndroid
