language: java
jdk: oraclejdk7

env:
  global:
    - ANDROID_BUILD_TOOLS=build-tools-18.0.1
  matrix:
    - ANDROID_SDK=android-10
    - ANDROID_SDK=android-17
    - ANDROID_SDK=android-18

before_install:
  # download the latest android sdk and unzip
  - sudo apt-get update -qq
  - if [ "`uname -m`" = "x86_64" ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget "http://dl.google.com/android/android-sdk_r22.0.4-linux.tgz" -O android-sdk.tgz
  - tar -zxf android-sdk.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo y | android update sdk --filter ${ANDROID_SDK},${ANDROID_BUILD_TOOLS},platform-tools --force --no-ui
  - android update project -p . --subprojects -t ${ANDROID_SDK} -n GatekeeperAndroid

script: ant debug

notifications:
  recipients:
    anthony+travisci@agargiulo.com

  irc:
    channels:
    - "skynet.csh.rit.edu#freshmen"
    template:
    - "%{repository}#%{build_number}: %{author}: %{branch}: %{message}"
